### PR TITLE
Replace deprecated cache properties in single-origin template

### PR DESCRIPTION
**Pull request by farski**
Replaces some deprecated properties (DefaultTTL, MaxTTL, MinTTL, ForwardedValued) with new CachePolicy and OriginRequestPolicy resources.

This allows for more granular control over differences between caching behavior and origin request behavior. It also allows support for newer features, like Brotli compression.

Builds will fail until cfn-lint catches up on Brotli support.

### CODE REVIEW

**Review by cavis — APPROVED** [review]
👍 looks right to me.

Is the plan to update existing distributions then?  Looks like you can switch between them in the CloudFront web UI ... so you'd think it would just work, since you kept the input params the same.

**Comment by farski** [comment]
I'm not going to go out of my way to redeploy every CDN we have. There may be a few that could particularly benefit from the Brotli compression, but as things eventually get redeployed my expectation is that this version of the template is entirely backwards compatible with the old one. I wouldn't think this would be the type of thing that CloudFormation can do in a single deploy; that wouldn't be great.

**Comment by cavis** [comment]
Makes sense.  Good sense!

**Comment by farski** [comment]
Going to try a deploy before merging

**Pull request merged**
